export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CART_DETAILS = "CART_DETAILS";
export const CART_COUNT = "CART_COUNT";
export const WISHLIST_DETAILS = "WISHLIST_DETAILS";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const DEALS_PRODUCT = "DEALS_PRODUCT";
export const RECOMMENTED_PRODUCT = "RECOMMENTED_PRODUCT";

